name: pet_feeder
description: "App para alimentar mascotas automaticamente"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  go_router: ^14.1.3
  google_maps_flutter: ^2.7.0
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_app_check: ^0.3.0+3
  geolocator: ^12.0.0
  pinput: ^5.0.0
  fluttertoast: ^8.2.6
  grouped_list: ^6.0.0
  gradient_icon: ^2.0.9
  iconify_flutter: ^0.0.5
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher-icon.png"

#dart run flutter_native_splash:create
flutter_native_splash:
  color: "#F2C879"
  image: "assets/images/splash-icon.png"
  android: true
  android_12:
    color: "#F2C879"
    image: "assets/images/splash-icon.png"