name: pet_feeder
description: "App para alimentar mascotas automaticamente"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher-icon.png"

#dart run flutter_native_splash:create
flutter_native_splash:
  color: "#F2C879"
  image: "assets/images/splash-icon.png"
  android: true
  web: true
  android_12:
    color: "#F2C879"
    image: "assets/images/splash-icon.png"